{% set name = "flytekitplugins-data-fsspec" %}
{% set version = "1.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flytekitplugins-data-fsspec-{{ version }}.tar.gz
  sha256: 2e0174c02aa5230c38544f97c614ebea056f27b2869137556a3a4d663f714202

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - flytekit >=1.0.0b3,<1.2.0
    - botocore >=1.7.48
    - fsspec >=2021.7.0

test:
  imports:
    - flytekitplugins.fsspec
  # commands:
  #   - pip check
  requires:
    - pip

about:
  home: https://github.com/flyteorg/flytekit/tree/master/plugins/flytekit-data-fsspec
  summary: This package provides data-plugins for flytekit, that are powered by fsspec
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  description: |
    `fsspec` powered data-plugins for Flytekit: `{{ name }}`

    PyPI: [https://pypi.org/project/flytekitplugins-data-fsspec/](https://pypi.org/project/flytekitplugins-data-fsspec/)

  doc_url: https://github.com/flyteorg/flytekit/tree/master/plugins
  dev_url: https://github.com/flyteorg/flytekit/tree/master/plugins/flytekit-data-fsspec

extra:
  recipe-maintainers:
    - sugatoray
